# Generated by Django 5.1.6 on 2025-02-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
