# Generated by Django 5.1.6 on 2025-02-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_userprofile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
