# Generated by Django 5.1.6 on 2025-02-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_userprofile_otp_created_at_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
